### ISSUE TITLE
kmalloc return value is never checked before its use

### ISSUE THREAD

**Issue by mlcrapkiller** [Exein-io/exein#2]
Hi,
this issue reports a bug in [1] where the return value from kmalloc is never checked before its use. To understand better the risk of this pattern please refer to [2,3]

[1] https://github.com/Exein-io/exein/blob/master/linux-4.14.162/security/exein/exein_lsm.c#L111
[2] https://www.viva64.com/en/b/0558/
[3] https://www.linuxjournal.com/article/6930

**Comment by alessandrocarminati** [comment]
Hello,
The issue you just opened gives us the opportunity to open a debate on this fact.
Kmalloc return address isn't checked not because we forgot to do it but is rather intentional.
I'll try to make my point:

The LSM needs to check the system behavior at any time. It can't just stop working and let the system go without it.
If a kmalloc fails, it means the LSM can't go forward and do its job.
It can't stop the system hoping something changes and hoping the system recovers by itself.
It can't either try to address the issue (actively doing something to make the next kmalloc succeed).

One path of action here would be to check the kmalloc return address and if it is NULL explicitly call panic.
But, in the other hand, if we don't perform the check and the kernel tries to use the kmalloc provided address, whatever it is, if it is NULL it will hit a NULL pointer dereference which in turn will crash the kernel.
One may ask if it's best to explicitly chrash the kernel, or let it crash form a NULL pointer dereference by itself.

Just a final small consideration:
Why an article on malloc (one of the links you included in your references), which is in user-space, should be pertinent to this issue?

**Comment by mlcrapkiller** [comment]
Hi,
so you are saying that a very well known security practice in your opinion is pointless?
that is interesting. Then a logic conclusion is that all the kmalloc checks in the kernel, the same that your product is using, are completely useless? 
If they are there in production mainline kernel, why they should not be present in your patch ?
Moreover, if you never free the memory soon or later things will go to hell...

**Comment by alessandrocarminati** [comment]
Hello,
You are mixing two different issues, the one in which we forgot a kfree,and another where we do not check the pointer after calling kmalloc.
 
About the first, we already acknowledged that in #4, and we specified that it is a known issue,
that has been delayed because others need to be fixed first.
 
About the second issue, I never said anywhere that security practices are pointless,
I just said that in this particular case, we choose the "not elegant" way of addressing the problem of not getting a good pointer from kmalloc.
 
According to Robert Love who writes about kmalloc on his "Linux Kernel Development" book,
"Kernel allocations always succeed unless an insufficient amount of memory is available.
Thus, you must check for NULL after all calls to kmalloc() and handle the error appropriately."
 
If you step in a low memory condition, the kernel may decide to sleep and swap memory to disk
if `GFP_KERNEL` is used as strategy.
Our targets can not perform a disk swap, they are embedded systems, and the situation of being handling an unknown hook in an unknown context does not allow it to put the system to sleep.
It would cause more problems than it solves.    
 
I may accept the objection that `GFP_ATOMIC` strategy might be more appropriate in such a scenario, but the reality is that the target we are aiming to run in can't swap to disk,
so it wouldn't actually make any difference.
 
Back to the problem where there's no check of the returned pointer;
 
Let's picture an scenario:
In the middle of a hook handling routine the kmalloc fails because we're out of memory.
What can we do?
The LSM can not proceed as it does not have enough space for putting its data.
Should the LSM quit?
It can't and, by the way, if it would try to do so it couldn't even do it properly given the circumstances. Also it is a security service, it can not quit by design.
 
Should the LSM try to address the memory shortage by actively doing something?
Not its business and, by the way, it can not be sure it will succeed, in this particular case, it is almost sure it will fail.
 
Should the LSM try to make the monitored process sleep?
That can't happen either. It can't assume anything about the monitored process.
The process could already be in a critical section holding locks for its own business.
 
So, if nothing else can be done, the only option that remains is to actively call panic().
 
What if, as we are doing now, the check is not performed? If the return address from kmalloc is not checked:
If kmalloc succeed, the LSM can just move forward and use its freshly allocated memory.
If kmalloc failed, the kernel will then try to dereference a NULL pointer.
What happens in such a situation? The kernel will panic.
 
Therefore, in this particular case, doing nothing is the same as checking the pointer and proactively panicking if it's NULL.

**Comment by mlcrapkiller** [comment]
basically what you are saying is that instead of crashing the userspace process (the one that triggered the syscall hooked by ExeinLSM) you prefer to make the kernel panic, correct?

**Comment by alessandrocarminati** [comment]
If the kernel found itself in a memory shortage situation, it is because memory is low with respect to the tasks the device must accomplish, or because of some software errors.
In such a case, yes, rather than killing the monitored process, we preferred to crash the system. Embedded devices are made to accomplish a specific task. A customers survey also points in that direction. Embedded systems producers prefer a short service down due to device reset than an extensive service shortage due to an idle system. 
To give you an example, a Linux-based RTU is useless without the "RTU" controlling process. Most of the time, these systems are unattended. There is no way to state if it is working correctly from the LSM point of view. So better to leave the system crash and reboot in a default condition.

**Comment by mlcrapkiller** [comment]
this doesn't make any sense. also because in the kernel there are plenty of places where the kmalloc return value is checked against NULL. so are you gonna to remove all of those to respect your statement?
